services:
  - type: web
    name: GHOST-RIDER-MD
    env: docker
    region: Frankfurt
    plan: free
    envVars:
      - key: SESSION_ID
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SUDO
        sync: false
